/**
 * The catalogue of cool numbers.
 *
 * Most entries are generated by rule so the club keeps growing on its own as
 * posthog/posthog burns through PR numbers -- pass a higher `max` and new
 * achievements appear. Hand-written entries in MEMES/MATH cover the numbers
 * that are only cool because humans decided they were.
 */

export const TIERS = {
  mythic: { label: 'Mythic', points: 100 },
  legendary: { label: 'Legendary', points: 50 },
  epic: { label: 'Epic', points: 25 },
  rare: { label: 'Rare', points: 10 },
}

export const CATEGORIES = {
  round: { label: 'Round numbers', blurb: 'Odometer moments. The whole repo holds its breath.' },
  repdigit: { label: 'Repdigits', blurb: 'Every digit the same. Nature is healing.' },
  staircase: { label: 'Staircases', blurb: 'Digits marching in single file, up or down.' },
  power: { label: 'Powers of two', blurb: 'Numbers that make a computer feel something.' },
  math: { label: 'Mathematical', blurb: 'Constants, curiosities, and famous integers.' },
  meme: { label: 'Memes & culture', blurb: 'Numbers that are funny for reasons nobody can defend.' },
}

/** Numbers that are cool purely by cultural decree. */
const MEMES = [
  [42, 'The Answer', 'To life, the universe, and everything.'],
  [69, 'Nice', 'Nice.'],
  [67, 'Six Seven', 'No further explanation has ever been offered.'],
  [88, 'Double Infinity', 'Two fat ladies.'],
  [404, 'Not Found', 'This PR could not be located. It was right there.'],
  [418, "I'm a Teapot", 'Short and stout, and RFC 2324 compliant.'],
  [420, 'Blaze It', 'A PR of leisure.'],
  [500, 'Internal Server Error', 'Something went wrong. Probably ClickHouse.'],
  [666, 'The Beast', 'Merged at your own peril.'],
  [777, 'Jackpot', 'Three cherries.'],
  [1337, 'Leet', 'Certified hacker PR.'],
  [1984, 'Big Brother', 'This PR is watching you.'],
  [2001, 'Space Odyssey', "I'm afraid I can't merge that, Dave."],
  [6969, 'Double Nice', 'Twice as nice.'],
  [8008, 'Calculator Classic', 'Type it, flip the calculator upside down, giggle.'],
  [9001, "It's Over 9000", 'What, nine thousand?!'],
  [12345, 'Luggage Combination', "That's the stupidest combination I've ever heard."],
  [13337, 'Extra Leet', 'Leet, but with more.'],
  [31337, 'Elite', 'The original spelling.'],
  [42069, 'The Grand Unified Meme', 'Both jokes at once. Peak numerology.'],
  [69420, 'The Other Grand Unified Meme', 'The same two jokes, reversed.'],
  [80085, 'Calculator Classic II', 'The calculator joke, all grown up.'],
  [90210, 'Beverly Hills', 'A PR from the right postcode.'],
  [6767, 'Six Seven Six Seven', 'It got worse.'],
  [676767, 'Six Seven, Ad Infinitum', 'It got much worse.'],
  [696969, 'Nice, Thrice', 'The nicest number the repo can currently hold.'],
  [42000, 'The Answer, Rounded', 'Approximately everything.'],
  [67000, 'Six Seven Thousand', 'A round number that is also deeply unserious.'],
  [69000, 'Nice Thousand', 'Nice, at scale.'],
  [4200, 'Blaze It, Rounded', 'Leisure, but tidier.'],
  [6900, 'Nice, Rounded', 'Nice, but tidier.'],
  [24601, 'Prisoner 24601', 'Who am I? A PR author, apparently.'],
  [1701, 'NCC-1701', 'To boldly ship what no one has shipped before.'],
  [2048, 'The Game', 'You just lost it. Also a power of two.'],
]

/** Numbers that are cool because mathematics says so. */
const MATH = [
  [314, 'Pi', 'The first three digits of a circle.'],
  [3141, 'Pi, Extended', 'Four digits deep.'],
  [31415, 'Pi, Serious Business', 'Five digits. This is a real commitment to pi.'],
  [31416, 'Pi, Rounded', 'For the pedants who round correctly.'],
  [314159, 'Pi, Fully Committed', 'Six digits of transcendence.'],
  [271, "Euler's Number", 'The base of natural growth.'],
  [2718, 'e, Extended', 'Compound interest, personified.'],
  [27182, 'e, Serious Business', 'Five digits of e.'],
  [161, 'Golden Ratio', 'Aesthetically optimal.'],
  [1618, 'Phi', 'The most beautiful proportion, allegedly.'],
  [16180, 'Phi, Extended', 'Divine proportion, five digits in.'],
  [1414, 'Root Two', 'The diagonal of a unit square.'],
  [14142, 'Root Two, Extended', 'Irrational and proud.'],
  [1729, 'The Taxicab Number', 'The smallest number expressible as two cubes, two ways.'],
  [6174, "Kaprekar's Constant", 'All roads lead here in four steps.'],
  [496, 'Perfect Number', 'Equal to the sum of its own divisors.'],
  [8128, 'Perfect Number', 'The fourth perfect number, and rarer than it looks.'],
  [5040, 'Seven Factorial', "Plato's favourite number."],
  [40320, 'Eight Factorial', '8! ways to arrange your commits.'],
  [1089, 'The Magic Number', 'Reverse it, subtract, and the magic trick works.'],
  [65535, 'Max Unsigned Short', 'One short of overflowing.'],
  [2147, 'Almost Max Int', 'The beginning of a very famous overflow.'],
]

const digits = (n) => String(n)

function isRepdigit(n) {
  const s = digits(n)
  return s.length >= 3 && [...s].every((d) => d === s[0])
}

function ordinalSuffix(n) {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return n + (s[(v - 20) % 10] || s[v] || s[0])
}

/** Round numbers: powers of ten, then every 10k once we are past 10k. */
function* roundNumbers(max) {
  for (let p = 1; p <= max; p *= 10) {
    yield {
      number: p,
      category: 'round',
      tier: 'mythic',
      name: p === 1 ? 'The First' : `PR #${p.toLocaleString('en-US')}`,
      blurb:
        p === 1
          ? 'Where it all began. The very first pull request.'
          : `The ${ordinalSuffix(String(p).length - 1)} power of ten. A genuine odometer moment.`,
    }
  }
  for (let n = 10000; n <= max; n += 10000) {
    if (String(n).match(/^10*$/)) continue // already claimed as a power of ten
    yield {
      number: n,
      category: 'round',
      tier: 'legendary',
      name: `${n / 1000}k`,
      blurb: `${(n / 1000).toLocaleString('en-US')} thousand pull requests deep.`,
    }
  }
}

/** Repdigits: 111, 4444, 99999, ... */
function* repdigits(max) {
  for (let len = 3; len <= String(max).length; len++) {
    for (let d = 1; d <= 9; d++) {
      const n = Number(String(d).repeat(len))
      if (n > max) continue
      yield {
        number: n,
        category: 'repdigit',
        tier: len >= 6 ? 'legendary' : len >= 5 ? 'epic' : 'rare',
        name: `${len} × ${d}`,
        blurb: `${len} identical digits in a row. The odds were not good.`,
      }
    }
  }
}

/** Staircases: runs of consecutive digits, ascending or descending. */
function* staircases(max) {
  for (let len = 4; len <= String(max).length; len++) {
    for (let start = 1; start <= 9; start++) {
      for (const dir of [1, -1]) {
        const ds = []
        for (let i = 0; i < len; i++) {
          const d = start + i * dir
          if (d < 0 || d > 9) break
          ds.push(d)
        }
        if (ds.length !== len) continue
        const n = Number(ds.join(''))
        if (n > max || String(n).length !== len) continue
        yield {
          number: n,
          category: 'staircase',
          tier: len >= 6 ? 'legendary' : len >= 5 ? 'epic' : 'rare',
          name: dir === 1 ? 'Staircase Up' : 'Staircase Down',
          blurb: `${len} consecutive digits, marching ${dir === 1 ? 'upwards' : 'downwards'}.`,
        }
      }
    }
  }
}

/** Powers of two, from 256 up. */
function* powersOfTwo(max) {
  for (let p = 256, e = 8; p <= max; p *= 2, e++) {
    yield {
      number: p,
      category: 'power',
      tier: p >= 65536 ? 'legendary' : p >= 4096 ? 'epic' : 'rare',
      name: `2^${e}`,
      blurb: `Two to the ${ordinalSuffix(e)}. A number with real binary dignity.`,
    }
  }
}

function* handwritten(max, list, category) {
  for (const [number, name, blurb] of list) {
    if (number > max) continue
    yield {
      number,
      category,
      tier: number >= 100000 ? 'legendary' : number >= 10000 ? 'epic' : 'rare',
      name,
      blurb,
      handwritten: true,
    }
  }
}

/** Tiers are ranked so that a better claim wins when two rules collide. */
const TIER_RANK = { mythic: 4, legendary: 3, epic: 2, rare: 1 }

/** Higher tier wins a collision; on a tie, a hand-written name beats a generated one. */
function beats(a, b) {
  if (TIER_RANK[a.tier] !== TIER_RANK[b.tier]) return TIER_RANK[a.tier] > TIER_RANK[b.tier]
  return Boolean(a.handwritten) && !b.handwritten
}

/**
 * Build the full catalogue up to `max`.
 *
 * A number can qualify under several rules (2048 is a power of two *and* a
 * meme). We keep one entry per number -- the highest tier wins -- but record
 * every rule it matched so the page can show them all.
 */
export function catalogue(max) {
  const byNumber = new Map()

  const all = [
    ...roundNumbers(max),
    ...repdigits(max),
    ...staircases(max),
    ...powersOfTwo(max),
    ...handwritten(max, MATH, 'math'),
    ...handwritten(max, MEMES, 'meme'),
  ]

  for (const entry of all) {
    const existing = byNumber.get(entry.number)
    if (!existing) {
      byNumber.set(entry.number, { ...entry, alsoKnownAs: [] })
      continue
    }
    const winner = beats(entry, existing) ? entry : existing
    const loser = winner === entry ? existing : entry
    byNumber.set(entry.number, {
      ...winner,
      alsoKnownAs: [...existing.alsoKnownAs, { name: loser.name, category: loser.category, blurb: loser.blurb }],
    })
  }

  return [...byNumber.values()]
    .map((e) => ({ ...e, points: TIERS[e.tier].points }))
    .sort((a, b) => a.number - b.number)
}

export { isRepdigit }
