/**
 * The catalogue of cool numbers.
 *
 * Most entries are generated by rule so the club keeps growing on its own as
 * posthog/posthog burns through PR numbers -- pass a higher `max` and new
 * achievements appear. Hand-written entries in MEMES/MATH cover the numbers
 * that are only cool because humans decided they were.
 */

/**
 * The club stops at a million. Past that the joke has run its course, and
 * #1000000 is a fine place for the odometer to retire.
 */
export const CEILING = 1_000_000

export const TIERS = {
  // One number in the entire catalogue sits here, and only one ever will.
  singularity: { label: 'Singularity', points: 1000 },
  mythic: { label: 'Mythic', points: 100 },
  legendary: { label: 'Legendary', points: 50 },
  epic: { label: 'Epic', points: 25 },
  rare: { label: 'Rare', points: 10 },
}

export const CATEGORIES = {
  round: { label: 'Round numbers', blurb: 'Odometer moments. The whole repo holds its breath.' },
  repdigit: { label: 'Repdigits', blurb: 'Every digit the same. Nature is healing.' },
  staircase: { label: 'Staircases', blurb: 'Digits marching in single file, up or down.' },
  power: { label: 'Powers of two', blurb: 'Numbers that make a computer feel something.' },
  math: { label: 'Mathematical', blurb: 'Constants, curiosities, and famous integers.' },
  meme: { label: 'Memes & culture', blurb: 'Numbers that are funny for reasons nobody can defend.' },
}

/**
 * Numbers that are cool purely by cultural decree.
 *
 * This list is public and it is about colleagues, so the bar for adding one is
 * that it would be fine read aloud in a company all-hands. Nothing that punches
 * at anyone's race, body, gender, or sexuality, and nothing that doubles as a
 * hate symbol -- that rules out 88, among others. When in doubt, leave it out;
 * the rule-generated categories have plenty of numbers already.
 */
const MEMES = [
  [42, 'The Answer', 'To life, the universe, and everything.'],
  [69, 'Nice', 'Nice.'],
  [67, 'Six Seven', 'No further explanation has ever been offered.'],
  [404, 'Not Found', 'This PR could not be located. It was right there.'],
  [418, "I'm a Teapot", 'Short and stout, and RFC 2324 compliant.'],
  [420, 'Blaze It', 'A PR of leisure.'],
  [500, 'Internal Server Error', 'Something went wrong. Probably ClickHouse.'],
  [666, 'The Beast', 'Merged at your own peril.'],
  [777, 'Jackpot', 'Three cherries.'],
  [1337, 'Leet', 'Certified hacker PR.'],
  [1984, 'Big Brother', 'This PR is watching you.'],
  [2001, 'Space Odyssey', "I'm afraid I can't merge that, Dave."],
  [6969, 'Double Nice', 'Twice as nice.'],
  [9001, "It's Over 9000", 'What, nine thousand?!'],
  [12345, 'Luggage Combination', "That's the stupidest combination I've ever heard."],
  [13337, 'Extra Leet', 'Leet, but with more.'],
  [31337, 'Elite', 'The original spelling.'],
  [42069, 'The Grand Unified Meme', 'Both jokes at once. Peak numerology.'],
  [69420, 'The Other Grand Unified Meme', 'The same two jokes, reversed.'],
  [90210, 'Beverly Hills', 'The ZIP code that got its own TV show.'],
  [6767, 'Six Seven Six Seven', 'It got worse.'],
  [676767, 'Six Seven, Ad Infinitum', 'It got much worse.'],
  [696969, 'Nice, Thrice', 'The nicest number the repo can currently hold.'],
  [42000, 'The Answer, Rounded', 'Approximately everything.'],
  [67000, 'Six Seven Thousand', 'A round number that is also deeply unserious.'],
  [69000, 'Nice Thousand', 'Nice, at scale.'],
  [4200, 'Blaze It, Rounded', 'Leisure, but tidier.'],
  [6900, 'Nice, Rounded', 'Nice, but tidier.'],
  [24601, 'Prisoner 24601', 'Who am I? A PR author, apparently.'],
  [1701, 'NCC-1701', 'To boldly ship what no one has shipped before.'],
  [2048, 'The Game', 'You just lost it. Also a power of two.'],
]

/**
 * Numbers that are cool because mathematics says so.
 *
 * Only irrational constants may be truncated, because their digits are the
 * recognisable thing, and they need five of them to count -- fewer than that is
 * a coincidence, not an achievement.
 *
 * Anything with an exact value (perfect numbers, factorials, max int) is listed
 * at that value or not at all. A truncation of an exact integer is just a
 * different integer: 21474 is not max int, it is 21474.
 */
const MATH = [
  [31415, 'Pi', 'Five digits of a circle.'],
  [31416, 'Pi, Rounded', 'For the pedants who round correctly.'],
  [314159, 'Pi, Fully Committed', 'Six digits of transcendence.'],
  [27182, "Euler's Number", 'The base of natural growth.'],
  [16180, 'Phi', 'The golden ratio, and allegedly the most beautiful proportion.'],
  [14142, 'Root Two', 'The diagonal of a unit square.'],
  [1729, 'The Taxicab Number', 'The smallest number expressible as two cubes, two ways.'],
  [6174, "Kaprekar's Constant", 'All roads lead here in four steps.'],
  [496, 'Perfect Number', 'Equal to the sum of its own divisors.'],
  [8128, 'Perfect Number', 'The fourth perfect number, and rarer than it looks.'],
  [5040, 'Seven Factorial', "Plato's favourite number."],
  [40320, 'Eight Factorial', '8! ways to arrange your commits.'],
  [362880, 'Nine Factorial', 'The last factorial that fits -- 10! overshoots the ceiling entirely.'],
  [1089, 'The Magic Number', 'Reverse it, subtract, and the magic trick works.'],
]

const digits = (n) => String(n)

function isRepdigit(n) {
  const s = digits(n)
  return s.length >= 3 && [...s].every((d) => d === s[0])
}

function ordinalSuffix(n) {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return n + (s[(v - 20) % 10] || s[v] || s[0])
}

/** Round numbers: powers of ten, then every 10k once we are past 10k. */
function* roundNumbers(max) {
  for (let p = 1; p <= max; p *= 10) {
    const final = p === CEILING
    yield {
      number: p,
      category: 'round',
      tier: final ? 'singularity' : 'mythic',
      name: final ? 'One in a Million' : p === 1 ? 'The First' : `PR #${p.toLocaleString('en-US')}`,
      blurb: final
        ? 'The millionth pull request. The machine prints exactly one of these, ever.'
        : p === 1
          ? 'Where it all began. The very first pull request.'
          : `The ${ordinalSuffix(String(p).length - 1)} power of ten. A genuine odometer moment.`,
    }
  }
  for (let n = 10000; n <= max; n += 10000) {
    if (String(n).match(/^10*$/)) continue // already claimed as a power of ten
    yield {
      number: n,
      category: 'round',
      tier: 'legendary',
      name: `${n / 1000}k`,
      blurb: `${(n / 1000).toLocaleString('en-US')} thousand pull requests deep.`,
    }
  }
}

/** Repdigits: 111, 4444, 99999, ... */
function* repdigits(max) {
  for (let len = 3; len <= String(max).length; len++) {
    for (let d = 1; d <= 9; d++) {
      const n = Number(String(d).repeat(len))
      if (n > max) continue
      yield {
        number: n,
        category: 'repdigit',
        tier: len >= 6 ? 'legendary' : len >= 5 ? 'epic' : 'rare',
        name: `${len} × ${d}`,
        blurb: `${len} identical digits in a row. The odds are not good.`,
      }
    }
  }
}

/**
 * Staircases: the digits 1 through n, counted up or back down.
 *
 * Only runs that start from 1 count. An offset run like 2345 or 6789 is the
 * same trick with a worse starting hand, and a dozen of them crowd out
 * everything else.
 */
function* staircases(max) {
  for (let len = 4; len <= String(max).length; len++) {
    const up = Array.from({ length: len }, (_, i) => i + 1)
    if (up.at(-1) > 9) break

    for (const dir of ['up', 'down']) {
      const ds = dir === 'up' ? up : [...up].reverse()
      const n = Number(ds.join(''))
      if (n > max) continue
      yield {
        number: n,
        category: 'staircase',
        tier: len >= 6 ? 'legendary' : len >= 5 ? 'epic' : 'rare',
        name: dir === 'up' ? 'Counting Up' : 'Countdown',
        blurb:
          dir === 'up'
            ? `Every digit from 1 to ${len}, in order.`
            : `${len}, ${len - 1}, and so on down to 1. Liftoff.`,
      }
    }
  }
}

/** Powers of two, from 256 up. */
function* powersOfTwo(max) {
  for (let p = 256, e = 8; p <= max; p *= 2, e++) {
    yield {
      number: p,
      category: 'power',
      tier: p >= 65536 ? 'legendary' : p >= 4096 ? 'epic' : 'rare',
      name: `2^${e}`,
      blurb: `Two to the ${ordinalSuffix(e)}. A number with real binary dignity.`,
    }
  }
}

function* handwritten(max, list, category) {
  for (const [number, name, blurb] of list) {
    if (number > max) continue
    yield {
      number,
      category,
      tier: number >= 100000 ? 'legendary' : number >= 10000 ? 'epic' : 'rare',
      name,
      blurb,
      handwritten: true,
    }
  }
}

/** Tiers are ranked so that a better claim wins when two rules collide. */
const TIER_RANK = { singularity: 5, mythic: 4, legendary: 3, epic: 2, rare: 1 }

/** Higher tier wins a collision; on a tie, a hand-written name beats a generated one. */
function beats(a, b) {
  if (TIER_RANK[a.tier] !== TIER_RANK[b.tier]) return TIER_RANK[a.tier] > TIER_RANK[b.tier]
  return Boolean(a.handwritten) && !b.handwritten
}

/**
 * Build the full catalogue up to `max`.
 *
 * A number can qualify under several rules (2048 is a power of two *and* a
 * meme). We keep one entry per number -- the highest tier wins -- but record
 * every rule it matched so the page can show them all.
 */
export function catalogue(requestedMax) {
  const max = Math.min(requestedMax, CEILING)
  const byNumber = new Map()

  const all = [
    ...roundNumbers(max),
    ...repdigits(max),
    ...staircases(max),
    ...powersOfTwo(max),
    ...handwritten(max, MATH, 'math'),
    ...handwritten(max, MEMES, 'meme'),
  ]

  for (const entry of all) {
    const existing = byNumber.get(entry.number)
    if (!existing) {
      byNumber.set(entry.number, { ...entry, alsoKnownAs: [] })
      continue
    }
    const winner = beats(entry, existing) ? entry : existing
    const loser = winner === entry ? existing : entry
    byNumber.set(entry.number, {
      ...winner,
      alsoKnownAs: [...existing.alsoKnownAs, { name: loser.name, category: loser.category, blurb: loser.blurb }],
    })
  }

  return [...byNumber.values()]
    .map((e) => ({ ...e, points: TIERS[e.tier].points }))
    .sort((a, b) => a.number - b.number)
}

export { isRepdigit }
